# .github/workflows/daily-tests.yml
name: Daily Selenium Tests

on:
  workflow_dispatch:
  schedule:
    - cron: '30 2 * * *'   # daily at 02:30 UTC
      # timezone: "Asia/Kolkata"   # optional if your GitHub Actions supports timezone

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  test-and-build-report:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Set up Java
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: '17'
          cache: maven

      - name: Run tests
        run: mvn -B clean test
        env: 
            HEADLESS: true

      - name: Install Allure
        if: always()
        run: |
          sudo apt-get install -y unzip
          curl -o allure.zip -L https://github.com/allure-framework/allure2/releases/latest/download/allure-2.29.0.zip
          unzip allure.zip
          sudo mv allure-2.29.0 /opt/allure
          sudo ln -s /opt/allure/bin/allure /usr/bin/allure

      - name: Generate Allure Report
        if: always()
        run: |
          allure generate allure-results --clean -o allure-report
          touch allure-report/.nojekyll
  
      - name: Upload Allure Pages artifact
        if: always()
        uses: actions/upload-pages-artifact@v4
        with:
          name: allure-report
          path: allure-report

      - name: Upload TestNG reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: testng-report
          path: |
            test-output/**
            target/surefire-reports/**

deploy:
  if: github.ref == 'refs/heads/main'
  needs: test-and-build-report
  runs-on: ubuntu-latest
  environment: 
     name: github-pages
     url:${{steps.deployment.outputs.page_url}}

  steps:
     -name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4
