# .github/workflows/daily-tests.yml
name: Daily Selenium Tests

on:
  workflow_dispatch:
  schedule:
    - cron: '30 2 * * *'   # daily at 02:30 UTC
      # timezone: "Asia/Kolkata"   # optional if your GitHub Actions supports timezone

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
          cache: maven

      - name: Run tests
        run: mvn -B clean test
        env: 
            HEADLESS: true

      - name: Upload TestNG reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: testng-report
          path: |
            test-output/**
            target/surefire-reports/**